"""customer add on

Revision ID: dacf350fb6cb
Revises: b4a9a730ec1d
Create Date: 2026-02-14 12:16:28.127288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dacf350fb6cb'
down_revision: Union[str, Sequence[str], None] = 'b4a9a730ec1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('visit_count', sa.Integer(), nullable=False))
    op.add_column('customer', sa.Column('total_spent', sa.Float(), nullable=False))
    op.add_column('customer', sa.Column('customer_since', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('order', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('order', 'served_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'served_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('order', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('customer', 'customer_since')
    op.drop_column('customer', 'total_spent')
    op.drop_column('customer', 'visit_count')
    # ### end Alembic commands ###
