"""try1

Revision ID: b4a9a730ec1d
Revises: 685e354c6061
Create Date: 2026-02-14 09:56:28.241269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a9a730ec1d'
down_revision: Union[str, Sequence[str], None] = '685e354c6061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tablesession', 'customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablesession', sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
