"""customer

Revision ID: da6c480a92c6
Revises: 9938d41c8719
Create Date: 2026-02-13 22:23:39.321190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6c480a92c6'
down_revision: Union[str, Sequence[str], None] = '9938d41c8719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tablesession', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tablesession', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tablesession', type_='foreignkey')
    op.drop_column('tablesession', 'customer_id')
    # ### end Alembic commands ###
